[package]
name = "hekateforge"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
hex = "0.4.3"
rand = "0.9.2"
rand_chacha = "0.9.0"
rand_core = "0.9.3"
rayon = "1.11.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
